# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install poetry
      run: pip3 install poetry

    - name: Install dependencies
      run: poetry install

    - name: Initialize MISPs
      run:  poetry run ./init_misps.py

    - name: Update hosts file
      run: |
       cat hosts_content | sudo tee -a /etc/hosts
       cat /etc/hosts

    - name: Setup nginx, after MISPs (so the internal network exists)
      run: |
        poetry run ./setup_nginx.py
        poetry run ./start_nginx.py

    - name: Initialize MISPs, take 2 (few scripts need to run before the interface is usable)
      run: |
        sleep 100
        ps aux
        poetry run ./init_misps.py

    - name: Test if the domains are reachable
      run: |
        curl --verbose --header 'Host: misp-central.local' 'http://127.0.0.1/users/login'
        curl --verbose --header 'Host: misp-1.local' 'http://127.0.0.1/users/login'
        curl --verbose --header 'Host: misp-2.local' 'http://127.0.0.1/users/login'
        curl --verbose --header 'Host: misp-3.local' 'http://127.0.0.1/users/login'

    - name: Run tests
      run: poetry run nosetests-3.4 testlive_sync.py
